### ISSUE TITLE
添加项目readme的建议

### ISSUE THREAD

**Issue by helunxing** [JamesFlare1212/GOSSIP#30]
现在看到项目首页，不知道这个项目运行在哪个URL上。

添加类似这样的内容到项目readme.md会很有帮助:
```markdown
# GOSSIP介绍
## 运行位置
本项目可以通过该URL访问：[neo.schoolmelon.com](neo.schoolmelon.com)
```

**Comment by JamesFlare1212** [comment]
是的，一直没机会写，我这几天完善一下

**Comment by JamesFlare1212** [comment]
https://github.com/JamesFlare1212/GOSSIP/commit/ec664dc29ce77429e492b46eeb4d623aa58675e1
